---
- name: Install Python dependencies
  sudo: true
  apt: name={{ item }} state=latest
  with_items:
    - libffi-dev
    - gcc
- include: deadsnakes.yml
- include: pip.yml
- include: python-version.yml version=2.6
- include: python-version.yml version=3.3
- include: python-version.yml version=3.4
- include: python-version.yml version=2.7
- include: pypy.yml
- name: Install Python tools
  pip: name={{ item }}
  sudo: true
  with_items:
    - tox
    - detox
    - virtualenv
    - virtualenvwrapper
    - wheel
